### ISSUE TITLE
Sitemap showing information for draft pages

### ISSUE THREAD

**Issue by CrowdHailer** [github/pages-gem#139]
When setting up site maps through simply adding the gem to the _config.yml file the site map shows all my draft pages. Even though visiting the links included in the sitemap will return a 404 response.
I have added the following to my config.yml
```yml
gems:
  - jekyll-sitemap
```

**Comment by kleinfreund** [comment]
Can you try using front matter defaults as a workaround for now?

```yml
defaults:
  -
    scope:
      type: "drafts"
    values:
      sitemap: false
```

**Comment by CrowdHailer** [comment]
That doesn't appear to be working for me

**Comment by parkr** [comment]
try also adding `path`

```yml
defaults:
  -
    scope:
      path: "."
      type: "drafts"
    values:
      sitemap: false
```
