### ISSUE TITLE
make it easy to configure local Jekyll to be Pages-like

### ISSUE THREAD

**Issue by afeld** [github/pages-gem#200]
There were several changes in [the Jekyll 3.0 changeover](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0) that means that Jekyll needs a specific configuration to act the same locally as when the site is pushed to pages. A couple ideas about how to go about this:

* List the required configuration. As far as can tell, this would be

    ```yaml
    markdown: kramdown
    kramdown:
      input: GFM
    highlighter: rouge
    ```

* Offer a `github-pages serve` and `github-pages build`, which are a pass-through to the equivalent Jekyll commands, but with the `_config.yml` values overridden.

Thoughts?
