### ISSUE TITLE
Amend `site.url` to Pages configuration

### ISSUE THREAD

**Issue by parkr** [github/pages-gem#26]
Not sure what the possibility of this is, but it'd be cool to see the config file that the Pages build process passes in to Jekyll to set `site.url` based on the CNAME or repo name. This would make it easier to use `site.url` locally then push up and have them change.

Considering Pages (through DynDNS) controls the FQDNs for Pages sites, this seems reasonable.

The only downside is that it requires runtime input of the entries in DynDNS.

Possibilities, depending upon the repo:

``` yml
# no CNAME
url: http://parkr.github.io
# no CNAME, no CNAME for user pages
url: http://parkr.github.io/project-name

# CNAME for user pages
url: http://blog.parkermoore.de
# No CNAME, CNAME for user pages
url: http://blog.parkermoore.de/project-name
```
