### ISSUE TITLE
[Github Pages] Modify headers, respect _config.yml webrick headers

### ISSUE THREAD

**Issue by laukstein** [github/pages-gem#415]
Github Pages in Github system doesn't respect _config.yml headers settings:

```
webrick:
    headers:
        Referrer-Policy: no-referrer
        X-Frame-Options: SAMEORIGIN
        X-XSS-Protection: 1
```

and adds different headers like "access-control-allow-origin: *" for all resources, that is considered as harmful.

![grabilla ya6264](https://cloud.githubusercontent.com/assets/183966/23116022/ff3c96de-f750-11e6-955e-24f432365780.png)

### This issue affects

- [x] The site generated by GitHub Pages
- [ ] Building sites locally
